Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  # Shared private network
  NETWORK = "192.168.56"

  # -------------------------
  # MASTER NODE
  # -------------------------
  config.vm.define "master" do |master|
    master.vm.hostname = "k3s-master"
    master.vm.network "private_network", ip: "#{NETWORK}.10"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-master"
      vb.memory = 2048
      vb.cpus = 2
    end

    master.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --tls-san #{NETWORK}.10" sh -
      
      # save node token for worker
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
    SHELL
  end

  # -------------------------
  # WORKER NODE
  # -------------------------
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "k3s-worker"
    worker.vm.network "private_network", ip: "#{NETWORK}.11"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-worker"
      vb.memory = 2048
      vb.cpus = 2
    end

    worker.vm.provision "shell", inline: <<-SHELL
      # wait for master token file
      while [ ! -f /vagrant/node-token ]; do
        echo "Waiting for token..."
        sleep 5
      done

      TOKEN=$(cat /vagrant/node-token)

      curl -sfL https://get.k3s.io | K3S_URL="https://#{NETWORK}.10:6443" K3S_TOKEN=$TOKEN sh -
    SHELL
  end

end
