apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rrhnizar-app-sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rhnizar/argocd_app_rrhnizar
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true