Vagrant.configure("2") do |config|

  config.vm.define "kchaoukiS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "kchaoukiS"

    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "kchaoukiS"
      vb.memory = 2048
      vb.cpus = 2
    end

    server.vm.provision "shell", path: "scripts/script.sh"
  end

end
