Vagrant.configure("2") do |config|

  # Shared variables
  SERVER_IP = "192.168.56.110"
  TOKEN     = "ael-amin-cluster-token"

  # =========================
  # Machine 1: Controller
  # =========================
  config.vm.define "ael-aminS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "ael-aminS"
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "ael-aminS"
    end

    server.vm.provision "shell", inline: <<-SHELL
      apt update -y
      apt install -y curl

      # Install K3s in server mode
      curl -sfL https://get.k3s.io | \
      INSTALL_K3S_EXEC="server --node-ip=#{SERVER_IP}" \
      K3S_TOKEN="#{TOKEN}" sh -

      echo "K3s controller ready"
    SHELL
  end

  # =========================
  # Machine 2: Agent
  # =========================
  config.vm.define "ael-aminSW" do |worker|
    worker.vm.box = "debian/bookworm64"
    worker.vm.hostname = "ael-aminSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "ael-aminSW"
    end

    worker.vm.provision "shell", inline: <<-SHELL
      apt update -y
      apt install -y curl

      # Wait for server API to be reachable
      until nc -z #{SERVER_IP} 6443; do
        sleep 3
      done

      # Install K3s agent
      curl -sfL https://get.k3s.io | \
      K3S_URL="https://#{SERVER_IP}:6443" \
      K3S_TOKEN="#{TOKEN}" \
      INSTALL_K3S_EXEC="agent --node-ip=192.168.56.111" sh -

      echo "K3s agent joined"
    SHELL
  end

end